Map<String, String> map_text = {
  "GN":
      "Use the bat shape favoured by professionals with the Hypernova 1.0 Players cricket bat. With mid-to-low sweetspot and a long and sweeping spine, the Hypernova is designed for maximum impact at the crease. Imposing edges give even mistimed shots the chance to clear the ropes, while the flat face gives the bat an increased profile. Speed and power come as standard with the Hypernova cricket bat thanks to the low balance point and innovative shaping. The aesthetic of Hypernova is stunning, with a metallic red and fluorescent red combination, complimented by tonal blues for an eye-catching finish.Take your game to another level this summer with our new Hypernova 1.0 Players Cricket Bat.",
  "GM":
      "Unleash your true potential with the GM Prodigy 2.0 Players cricket bat. Crafted with precision and finesse, this bat features a mid-to-high sweetspot and a perfectly balanced design for optimum performance at the crease. The commanding edges ensure that every shot, even those off-center, has the power to sail over the boundary ropes. The flat face increases the bat's profile, providing a formidable presence on the pitch. Experience the perfect fusion of speed and power with the Prodigy 2.0, boasting a low balance point and innovative shaping. The aesthetics are unmatched, showcasing a sleek blend of classic white and silver, creating a visually striking masterpiece. Elevate your game with the GM Prodigy 2.0 Players Cricket Bat and dominate the field this season.",
  "NB":
      "Step into the realm of excellence with the NB Fury 3.0 Players cricket bat. Meticulously designed to meet the demands of professional players, this bat features a mid-to-low sweetspot and an extended sweeping spine for maximum impact at the crease. The generously sized edges provide unparalleled power, ensuring even mistimed shots clear the boundary effortlessly. The flat face not only enhances the bat's profile but also delivers consistent performance. The low balance point and cutting-edge shaping guarantee exceptional speed and power. The NB Fury 3.0 boasts a stylish design with a dynamic combination of bold black and electric blue, making a statement on the pitch. Elevate your game and leave a lasting impression with the NB Fury 3.0 Players Cricket Bat.",
  "SS":
      "Unleash your cricketing prowess with the SS Gladiator Players cricket bat. Engineered to perfection, this bat features a mid-to-high sweetspot and a sweeping spine for maximum impact. The commanding edges provide unparalleled power, allowing even mistimed shots to clear the ropes effortlessly. The flat face increases the bat's profile, ensuring a dominating presence at the crease. The SS Gladiator is synonymous with speed and power, thanks to its low balance point and innovative shaping. The aesthetics are captivating, with a striking combination of fiery red and midnight black, creating a bat that demands attention. Take your game to new heights with the SS Gladiator Players Cricket Bat and experience cricketing excellence like never before.",
  "KK":
      "Embark on a cricketing journey like never before with the Kookaburra Surge 1.0 Players cricket bat. Designed for professionals, this bat features a mid-to-low sweetspot and an extended spine for maximum impact at the crease. The imposing edges ensure that every shot, regardless of timing, has the potential to clear the boundary with ease. The flat face not only enhances the bat's profile but also guarantees consistent performance. Speed and power are non-negotiable with the Surge 1.0, thanks to its low balance point and cutting-edge shaping. The aesthetics are unparalleled, with a vibrant lime green and deep navy blue combination, creating a bat that stands out on the pitch. Elevate your game with the Kookaburra Surge 1.0 Players Cricket Bat and redefine your cricketing experience",
  "NONE": "there is an error!! please contact at 000999888777666",
};
